In [4]:
import numpy as np
import matplotlib.pyplot as plt
from scipy.signal import convolve2d

F = np.array([
    [5, 3, 1, 0, 9],
    [12, 4, 1, 0, 2],
    [5, 3, 1, 0, 2],
    [5, 21, 1, 0, 1],
    [0, 0, 1, 0, 9],
])
W = np.array([
    [1, 0, 1],
    [29, 1, 0.5],
    [0, 1, 1],
])

# Convolution
C = convolve2d(F, W, mode='valid')
print(C)

# [[53.  10.  62.5]
#  [56.5 28.5 61.5]
#  [61.5 15.5 40.5]]

[[53.  10.  62.5]
 [56.5 28.5 61.5]
 [61.5 15.5 40.5]]
